apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: gmr-consolidator
  labels:
    app: gmr-consolidator
spec:
  type: ClusterIP
  selector:
    app: gmr-consolidator
  ports:
    - name: http
      port: 8000
      targetPort: 8000
